[
    {
        "id": 583246192,
        "name": "CVE-2020-24584",
        "full_name": "Live-Hack-CVE\/CVE-2020-24584",
        "owner": {
            "login": "Live-Hack-CVE",
            "id": 121191732,
            "avatar_url": "https:\/\/avatars.githubusercontent.com\/u\/121191732?v=4",
            "html_url": "https:\/\/github.com\/Live-Hack-CVE"
        },
        "html_url": "https:\/\/github.com\/Live-Hack-CVE\/CVE-2020-24584",
        "description": "An issue was discovered in Django 2.2 before 2.2.16, 3.0 before 3.0.10, and 3.1 before 3.1.1 (when Python 3.7+ is used). The intermediate-level directories of the filesystem cache had the system's standard umask rather than 0o077. CVE project by @Sn0wAlice",
        "fork": false,
        "created_at": "2022-12-29T07:44:18Z",
        "updated_at": "2022-12-29T07:44:18Z",
        "pushed_at": "2022-12-29T07:44:20Z",
        "stargazers_count": 0,
        "watchers_count": 0,
        "has_discussions": false,
        "forks_count": 0,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [],
        "visibility": "public",
        "forks": 0,
        "watchers": 0,
        "score": 0
    }
]